# Maintainer: dr460nf1r3 <dr460nf1r3 at garudalinux dot org>

pkgname=kde-git-meta
pkgver=4
pkgrel=1
arch=('any')
url="https://chaotic.cx"
license=('GPL')
pkgdesc="Meta package for a full Plasma-git installation"
replaces=(kde-git)
depends=(attica-git
        baloo-git
        bluedevil-git
        breeze-git
        breeze-icons-git
        dolphin-git-git
        frameworkintegration-git
        kaccounts-integration-git
        kactivities-git
        kactivities-stats-git
        kactivitymanagerd-git
        karchive-git
        kate-git
        kauth-git
        kbookmarks-git
        kcmutils-git
        kcodecs-git
        kcolorpicker-git
        kcompletion-git
        kconfig-git
        kconfigwidgets-git
        kcontacts-git
        kcoreaddons-git
        kcrash-git
        kdbusaddons-git
        kde-gtk-config-git
        kdeclarative-git
        kdeconnect-git
        kdecoration-git
        kded-git
        kdelibs4support-git
        kdeplasma-addons-git
        kdesu-git
        kdialog-git
        kdnssd-git
        kdoctools-git
        kdsoap-git
        kdsoap-ws-discovery-client-git
        kemoticons-git
        kfilemetadata-git
        kgamma5-git
        kglobalaccel-git
        kguiaddons-git
        khelpcenter-git
        kholidays-git
        khotkeys-git
        khtml-git
        ki18n-git
        kiconthemes-git
        kidletime-git
        kimageannotator-git
        kimageformats-git
        kinfocenter-git
        kinit-git
        kio-extras-git
        kio-git
        kirigami2-git
        kitemmodels-git
        kitemviews-git
        kjobwidgets-git
        kjs-git
        kjsembed-git
        kmenuedit-git
        knewstuff-git
        knotifications-git
        knotifyconfig-git
        konsole-git-git
        kpackage-git
        kparts-git
        kpeople-git
        kpeoplevcard-git
        kpty-git
        krunner-git
        kscreen-git
        kscreenlocker-git
        kservice-git
        ksystemstats-git
        ksystemstats-git
        ktexteditor-git
        ktextwidgets-git
        kunitconversion-git
        kuserfeedback-git
        kvantum-qt5-git
        kwallet-git
        kwallet-pam-git
        kwayland-git
        kwayland-integration-git
        kwidgetsaddons-git
        kwin-git
        kwindowsystem-git
        kxmlgui-git
        kxmlrpcclient-git
        libkscreen-git
        libksysguard-git
        milou-git
        modemmanager-qt-git
        networkmanager-qt-git
        plasma-browser-integration-git
        plasma-desktop-git
        plasma-disks-git
        plasma-firewall-git
        plasma-framework-git
        plasma-integration-git
        plasma-nm-git
        plasma-pa-git
        plasma-wayland-session-git
        plasma-workspace-git
        polkit-kde-agent-git
        poppler-glib-git
        poppler-qt5-git
        powerdevil-git
        prison-git
        purpose-git
        qca-git
        qqc2-desktop-style-git
        signon-kwallet-extension-git
        solid-git
        sonnet-git
        spectacle-git
        syntax-highlighting-git
        systemsettings-git
        threadweaver-git
        xdg-desktop-portal-kde-git)
