#!/usr/bin/env bash

paru -G adwaita-qt-git \
ant-dracula-kde-theme-git \
ant-dracula-theme-git \
apparmor-git \
apple-music-electron-git \
arch-audit-git \
attica-git \
baloo-git \
birdtray-git \
bleachbit-git \
bluedevil-git \
breeze-git \
breeze-icons-git \
ckb-next-git \
contour-git \
cutefish-git \
disman-git \
dolphin-git \
exa-git \
fastfetch-git \
fbneo-git \
ffmpeg-full-git \
findex-git \
firejail-git \
fish-git \
frameworkintegration-git \
ftxui-git \
git-git \
kaccounts-integration-git \
kactivities-git \
kactivities-stats-git \
kactivitymanagerd-git \
karchive-git \
kate-git \
kauth-git \
kbookmarks-git \
kcmutils-git \
kcodecs-git \
kcolorpicker-git \
kcompletion-git \
kconfig-git \
kconfigwidgets-git \
kcontacts-git \
kcoreaddons-git \
kcrash-git \
kdbusaddons-git \
kdeclarative-git \
kdeconnect-git \
kdecoration-git \
kded-git \
kde-gtk-config-git \
kdelibs4support-git \
kdeplasma-addons-git \
kdsoap-ws-discovery-client-git \
keepassxc-git \
kemoticons-git \
kfilemetadata-git \
kgamma5-git \
kglobalaccel-git \
kguiaddons-git \
khelpcenter-git \
kholidays-git \
khotkeys-git \
khtml-git \
ki18n-git \
kiconthemes-git \
kidletime-git \
kimageannotator-git \
kimageformats-git \
kinfocenter-git \
kinit-git \
kio-extras-git \
kio-git \
kirigami2-git \
kitemmodels-git \
kitemviews-git \
kjobwidgets-git \
kjsembed-git \
kjs-git \
kmenuedit-git \
knewstuff-git \
knotifications-git \
knotifyconfig-git \
konsole-git \
kpackage-git \
kparts-git \
kpeople-git \
kpeoplevcard-git \
kpty-git \
krunner-git \
kscreen-git \
kscreenlocker-git \
kservice-git \
ksystemstats-git \
ktexteditor-git \
ktextwidgets-git \
kunitconversion-git \
kuserfeedback-git \
kvantum-qt5-git \
kwallet-git \
kwallet-pam-git \
kwayland-git \
kwayland-integration-git \
kwidgetsaddons-git \
kwin-bismuth-git \
kwindowsystem-git \
kwinft-git \
kwin-git \
kxmlgui-git \
kxmlrpcclient-git \
lib32-mesa-git \
libksysguard-git \
libretro-fbneo-git \
lightly-git \
llvm-git \
mesa-git \
milou-git \
modemmanager-qt-git \
mullvad-vpn-beta
networkmanager-qt-git \
noisetorch-git \
openrazer-git \
openrgb-git \
pacui-git \
phoronix-test-suite-git \
pipewire-full-git \
poppler-git \
powerdevil-git \
prison-git \
kwinft-git \
proton \
proton-experimental \
wine-ge-custom \
proton-ge-custom \
qbittorrent-enhanced-git \
qgnomeplatform-git \
qqc2-desktop-style-git \
signon-kwallet-extension-git \
solid-git \
sonnet-git \
spectacle-git \
syntax-highlighting-git \
systemsettings-git \
threadweaver-git \
v4l2loopback-dkms-git \
wayland-git \
wlroots-git \
wrapland-git \
zellij-git

files=$(find . -name "PKGBUILD")

for f in $files
do
        d=$(dirname $f)
        echo "makepkg -src --sign --skipinteg --noconfirm $f"
        cd $d
        docker run --name dockerbuild -e EXPORT_PKG=1 -v $PWD:/pkg -v /home/ptr1337/ccache:/home/notroot/ccache pttrr/docker-makepkg
        docker rm dockerbuild
        cd ..
done

mv */*.tar.zst* /home/ptr1337/packages/
